development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ezfeed_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ezfeed_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ezfeed_production
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *test